# Generated by Django 3.1.2 on 2021-02-03 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('home', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('langue', models.CharField(max_length=255)),
            ],
        ),
    ]
