# Generated by Django 3.1.6 on 2021-02-04 14:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaveTripPoints',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('trajet', models.CharField(max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('pts', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
