# Generated by Django 3.1.6 on 2021-02-04 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_savetrippoints_statut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savetrippoints',
            name='statut',
            field=models.CharField(choices=[('Validé', 'validated'), ('En attente', 'waiting'), ('Refusé', 'refused')], max_length=100),
        ),
    ]
